# Generated by Django 4.0.4 on 2022-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilterChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(choices=[('Not Delivered', 'Not Delivered'), ('Delivered', 'Delivered'), ('Not Dispatched', 'Not Dispatched'), ('Dispatched', 'Dispatched')], max_length=100)),
            ],
        ),
    ]
