# Generated by Django 4.0.4 on 2022-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Genocide', 'Genocide'), ('Assasination', 'Assasination'), ('Silent', 'Silent'), ('Standard', 'Standard Equipment')], default='Standard', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='itemPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'danger'), ('S', 'secondary'), ('P', 'primary'), ('ss', 'success')], default='D', max_length=500),
        ),
    ]
