# Generated by Django 4.0.4 on 2022-05-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_item_quantity_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemDiscountPrice',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
