# Generated by Django 4.0.4 on 2022-05-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_item_itemdiscountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sulg',
            field=models.SlugField(default='Item'),
        ),
    ]
