# Generated by Django 4.0.4 on 2022-05-20 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_item_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sulg',
            new_name='slug',
        ),
    ]
