# Generated by Django 4.0.4 on 2022-05-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_order_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
