# Generated by Django 4.0.4 on 2022-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_item_coupon_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='coupon_discount_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
