# Generated by Django 4.0.4 on 2022-05-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_item_coupon_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(blank=True, max_length=500, null=True)),
                ('coupon_discount_percentage', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='item',
            name='coupon_discount_percentage',
        ),
    ]
