# Generated by Django 4.0.4 on 2022-05-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Refund_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Refund_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='dispatched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='preproccessing',
            field=models.BooleanField(default=False),
        ),
    ]
