# Generated by Django 4.0.4 on 2022-05-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_order_paid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='refund_ammount',
            field=models.IntegerField(default=0),
        ),
    ]
