# Generated by Django 4.0.4 on 2022-05-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_refund_refund_ammount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='refund_ammount',
            field=models.FloatField(default=0),
        ),
    ]
