# Generated by Django 4.0.4 on 2022-05-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_refund_requested_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Refund_Worker_Dispatched',
            field=models.BooleanField(default=False),
        ),
    ]
