# Generated by Django 4.0.4 on 2022-05-26 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_order_refund_worker_dispatched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Refund_Worker_Dispatched',
            new_name='RefundWorkerDispatched',
        ),
    ]
